### ISSUE TITLE
Duplicate repos

### ISSUE THREAD

**Issue by johnnyshields** [gtd/csv_builder#13]
@gtd this is a fantastic gem!

I had quite a bit of trouble locating this repo however. If I google "csv_builder", these two repos are the top results:

econsultancy/csv_builder
teambox/csv_builder

May I suggest you ask the owners of these to delete their readmes and put a note which links to gtd/csv_builder. (econsultancy is pointing to https://github.com/dasil003/csv_builder, which is dead)

**Comment by reiz** [comment]
:+1:

**Comment by reiz** [comment]
@johnnyshields This project looks dead to me. /cc @gtd

**Comment by gtd** [comment]
Yeah I changed my GitHub username and broke many links a while ago (I promise not to do it again).

As far as the project is concerned, definitely not dead, I am still using it at my day job. I have not been the most reliable maintainer, but I believe in good maintenance and I'm still commiting myself to it, so I'm flagging this repo to come back and respond to the two open issues.  Thanks for bumping this one to get it back on my radar.

**Comment by reiz** [comment]
@gtd I just saw that the last commit was from 2012, that's why I thought this is a dead project. And the last stable release is [3 years old](https://www.versioneye.com/ruby/csv_builder/2.1.1). Does it still work with rails 4 and ruby 2.2.2? In the README the requirements section says it needs rails 3. 

At [VersionEye](https://www.versioneye.com) there is a PDF Export for the [license whitelist feature](http://blog.versioneye.com/2014/09/15/license-whitelist/). I would like to offer a CSV download as well and your project looked like a good candidate for the implementation. But I stopped when I saw that the last stable release was 3 years ago :-)

**Comment by gtd** [comment]
Just to close the loop here: although I haven't personally been using this gem recently, I believe it's still in active use in several projects that have been upgrading through the Rails versions over the years without breakage.  I think the surface area is small enough that this gem doesn't require a ton of maintenance, but I am still here if anything comes up.  I just merged and released a patch for a Rails 6 deprecation.  This also updates the last reference I'm aware of to the old repo URL, so this should also be more discoverable going forward.
